apiVersion: v1
kind: Service

metadata:
  name: fleetman-queue
  namespace: default

spec:
  selector:
    app: fleetman-queue

  type: ClusterIP

  ports:
    - name: http
      port: 8161

    - name: endpoint
      port: 61616

---
apiVersion: v1
kind: Service

metadata:
  name: fleetman-position-tracker
  namespace: default

spec:
  selector:
    app: fleetman-position-tracker

  type: ClusterIP

  ports:
    - name: http
      port: 8080

---
apiVersion: v1
kind: Service

metadata:
  name: fleetman-api-gateway
  namespace: default

spec:
  selector:
    app: api-gateway

  type: ClusterIP

  ports:
    - name: http
      port: 8080

---
apiVersion: v1
kind: Service

metadata:
  name: web-app
  namespace: default

spec:
  selector:
    app: web-app

  # local testing
  # type: ClusterIP
  type: LoadBalancer

  ports:
    - name: web-app
      protocol: TCP
      port: 80
