apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-storage
  namespace: default
  labels:
    app: mongodb
spec:
  # local link to Volume
  storageClassName: mongodb

  # cloud link to volume
  # storageClassName: cloud-ssd

  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
# for testing on local
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-volume
spec:
  hostPath:
    path: /mongo-data
    type: DirectoryOrCreate
  storageClassName: mongodb
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce

---
# for testing on the cloud
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: cloud-ssd
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp2
